// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRwNUSnm2hQWc6-Uqe48Rcl8hhSdvfus',
    appId: '1:246677338710:web:0be8b5868cdfd28c7559f7',
    messagingSenderId: '246677338710',
    projectId: 'locator-6b886',
    authDomain: 'locator-6b886.firebaseapp.com',
    storageBucket: 'locator-6b886.appspot.com',
    measurementId: 'G-72Y55TP3FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8F2WX_L3HpE4OZX3fkr3F4CnEeE2OVo',
    appId: '1:246677338710:android:0be67ff732bc5c6c7559f7',
    messagingSenderId: '246677338710',
    projectId: 'locator-6b886',
    storageBucket: 'locator-6b886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVpxsDlNhuH-jbNBHtqorH-RWdw89uVI',
    appId: '1:246677338710:ios:01550fdb794df4c37559f7',
    messagingSenderId: '246677338710',
    projectId: 'locator-6b886',
    storageBucket: 'locator-6b886.appspot.com',
    iosBundleId: 'com.example.locator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVpxsDlNhuH-jbNBHtqorH-RWdw89uVI',
    appId: '1:246677338710:ios:b7bbeea5edf1aba27559f7',
    messagingSenderId: '246677338710',
    projectId: 'locator-6b886',
    storageBucket: 'locator-6b886.appspot.com',
    iosBundleId: 'com.example.locator.RunnerTests',
  );
}
